In [2]:
import numpy as np

In [3]:
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
# 使用transpose转置
np.transpose(arr)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [5]:
arr1 = ([1,2,3,4])
arr1

[1, 2, 3, 4]

In [6]:
# 一维数组使用转置和不用效果是一样的
np.transpose(arr1)

array([1, 2, 3, 4])

In [7]:
# 使用数组对象.T实现转置
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 数组常见操作

#### 1.数组排序

numpy.sort(a, axis = -1, kind = None, order = None)  
参数含义：  
**a**:需要进行排序的数组  
**axis**:需要操作的轴，如果为0表示的是行，如果是1表示的是列  
kind：排序算法，可选参数:'quicksort','mergesort','heapsort','stable'.分别表示：快速排序，归并排序，堆排序，稳定排序  
order：指定字段名排序  
使用方法：
1.numpy.sort(数组）
2.数组.sort()

In [8]:
num = np.array([1,5,3,4,6,0])
num

array([1, 5, 3, 4, 6, 0])

In [9]:
np.sort(num)

array([0, 1, 3, 4, 5, 6])

In [ ]:
# 使用数组.sort()来排序
num.sort()

numpy.sort(数组)2种方式的区别数组.sort();   
nupy.sort(数组)：不会对原数据进行修改，而是返回新的数据。  
数组.sort()：直接修改原数据，不会返回值。

####　2.添加数据

numpy.append(arr, values, axis = None)  
arr:数组  
values:需要添加的值  
axis：轴  
注意：  
1.如果axis没有指定值，那么arr和values都会被铺平（都会被展开成一维数组），然后再添加。如果说指定了值，那么就会在对应的轴上进行添加操作。
2.在添加数据的时候需要注意arr和values的维度需要相同，以及values的长度需要arr对应轴方向上的数据长度相同。

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 不指定axis参数添加
np.append(arr2,[0,0,0])

array([1, 2, 3, 4, 5, 6, 0, 0, 0])

In [14]:
# 指定轴进行添加
np.append(arr2,[[2,2,2]],  
          #对行进行操作
          axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 2]])

In [18]:
np.append(arr2, [[0],[0]],axis = 1)

array([[1, 2, 3, 0],
       [4, 5, 6, 0]])

2.numpy.insert(arr,obj,values,axis=None)  
arr:数组对象  
obj:插入元素的位置,值不能大于数据对应维度的长度  
values:值，被插入的数据  
axis：轴

In [21]:
arr3 = np.array([1,2,3,4])
arr3

array([1, 2, 3, 4])

In [23]:
np.insert(arr3,0,0,axis=0)

array([0, 1, 2, 3, 4])

In [25]:
arr4 = np.arange(12).reshape(4,3)
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
np.insert(arr4,1,10,axis=0)

array([[ 0,  1,  2],
       [10, 10, 10],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.insert(arr4,1,10,axis=1)

array([[ 0, 10,  1,  2],
       [ 3, 10,  4,  5],
       [ 6, 10,  7,  8],
       [ 9, 10, 10, 11]])

#### 3.数组删除

numpy.delete(arr. obj, axis=None)  
arr:数组  
obj:需要删除的数据的位置 
axis：轴

In [30]:
arr5 = np.arange(1,13).reshape(3,4)
arr5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# 删除指定行
np.delete(arr5,1,axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [33]:
# 删除指定列
np.delete(arr5,1,axis = 1)

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

#### 4.去重
numpy.unique(ar,axis=None)  
ar：数组
axis:轴

In [34]:
arr6 = np.array([1,1,2,2,3,3])
arr6

array([1, 1, 2, 2, 3, 3])

In [35]:
b = np.unique(arr6)
b

array([1, 2, 3])

In [39]:
arr7=np.array([[1,2,2,4],
              [1,2,2,4],
              [5,2,2,8],
              [9,2,2,12]])
arr7

array([[ 1,  2,  2,  4],
       [ 1,  2,  2,  4],
       [ 5,  2,  2,  8],
       [ 9,  2,  2, 12]])

In [40]:
# 不指定axis的值
s = np.unique(arr7)
s

array([ 1,  2,  4,  5,  8,  9, 12])

In [42]:
# 只会删除数据全部相同的行或列
a = np.unique(arr7,axis=1)
a

array([[ 1,  2,  4],
       [ 1,  2,  4],
       [ 5,  2,  8],
       [ 9,  2, 12]])

####　5.数组的拼接

In [46]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [49]:
# 默认按行拼接
c = np.concatenate((a,b))
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
d = np.concatenate((a,b),axis = 1)
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### ６.数组的堆叠  
1.使用不同的函数名进行堆叠，不会扩展数据的维度，即原始数据是几维，堆叠之后还是几维

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [52]:
# 水平堆叠
ar = np.hstack((a,b))
ar

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [53]:
# 垂直堆叠
ar = np.vstack((a,b))
ar

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

２.使用函数np.stack((a1,a2,...),axis=0)进行堆叠，通过控制axis的值来控制堆叠方向  

np.stack()会扩展数据维度

In [55]:
ar2 = np.stack((a,b),axis=0)
ar2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
ar3 = np.stack((a,b),axis=1)
ar3

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [57]:
ar3.ndim

3

### 7.数组的拆分

np.hsplit(ary, indices_or_sections)  
ary:需要操作的数组  
indices_or_sections：数值表示需要将数据拆分成几个

In [59]:
# 数组的拆分
arr7 = np.arange(16).reshape(4,4)
print(arr7)
np.hsplit(arr7, 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
np.vsplit(arr7, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
# np.hsplit(arr7, 3) 无法将原数据分割成相等的3份，所以会报错  

np.split(ary, indices_or_sections,axis = 0)
ary：需要执行拆分操作的数组
indices_or_sections：数值表示需要将数据拆分成几个
axis：用来控制拆分的方向,默认是0

In [62]:
np.split(arr7, 4, axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [63]:
# help(np.split)

Help on function split in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    -------
    sub-arrays : list 

####　8.nan和inf

nan(Nan,NAN):表示的是空可以理解为None,由于nan不是一个数字所以nan与任何数字进行相关操作都会得到nan

In [66]:
np.nan+2

nan

In [67]:
np.nan*20

nan

In [69]:
np.nan == np.nan

False

因为nan不是一个具体的数据，所以2个不具体的数据进行相等判断的时候就会得到False

---

np.inf:表示无穷大，任何具体的数与inf进行大小判断永远小于inf

In [70]:
np.inf<10*1000

False

In [71]:
# 使用np.isnan()来判断
num = np.array([1,2,np.nan])
np.isnan(num)

array([False, False,  True])

### 常用统计函数

语法：  
数组对象.函数名（）

In [75]:
num2 = np.arange(20).reshape(4,5)
num2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
num2.sum()

190

### 条件逻辑

三元表达式：
x if c else y 
如果c为真则得到x，否则返回y

In [78]:
num3 = np.arange(10)
num3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
bol = np.where(num3%2 == 0,'偶数','奇数')
bol

array(['偶数', '奇数', '偶数', '奇数', '偶数', '奇数', '偶数', '奇数', '偶数', '奇数'],
      dtype='<U2')

### 通用函数

语法：np.函数名（数据）

In [81]:
np.sqrt(num3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [86]:
# 二元函数：np.函数（数组1，数组2）
num4 = np.arange(1,11)
num4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
np.add(num3,num4)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [91]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c