In [7]:
#导入Numpy
import numpy as np
import time

In [12]:
#python 代码
start_time = time.perf_counter()
lists=[]
for i in range(1000000):
    lists.append(i**(1/2))
end_time = time.perf_counter()
print('循环计算事件:', end_time-start_time)    

循环计算事件: 0.27623300000004747


In [14]:
start_time = time.perf_counter()
#创建numpy数组
arr = np.arange(1000000)
#计算arr中每一个数的平方根
c = np.sqrt(arr)
end_time = time.perf_counter()
print('循环计算事件:', end_time-start_time) #numpy效率比python代码高约60倍   

循环计算事件: 0.004625400000804802


In [15]:
0.27623300000004747/0.004625400000804802

59.72088899381328

In [ ]:
#shift+回车 就是运行

### 创建数组

语法：
    np.array('列表')
作用：就是将Python列表转为numpy数组  
如果有现成的列表或者数据量不大，那么可以使用这种方式创建

In [16]:
# 创建一维数组
# 1.直接传入列表的方式
arr = np.array([1,2,3,4,5])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [18]:
arr1 = np.array([])
arr1

array([], dtype=float64)

In [21]:
# 数组转列表
arr_list = list(arr)
print(type(arr_list))
arr_list

<class 'list'>


[1, 2, 3, 4, 5]

### 使用np.arange()创建
np.arange(起始值，结束值，步长)类似于range

In [24]:
arr2 = np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

### 如果只有一个变量需要输出，那么可以直接运行，不用print,                 可以偷懒，如果有多个变量还是要prin，否则只会输出最后一个值

### 使用np.linspace()创建等差数组
 linspace(start, stop, num=50, endpoint = True, retstep-False, dtype = None, axis=0)   
 start:起始值   
 stop：结束值     
 num：数值个数   
 dtype：指定数据类型   

In [27]:
# 创建等差数组，给定起始值，结束值， 数据个数，该函数会自动根据这3个值来计算公差
arr4 = np.linspace(2,3,num = 5)
arr4

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [29]:
# 创建2维数组
# 传入嵌套的列表
lis = [[1,2],[3,4],[5,6]]
arr_2 = np.array(lis)
arr_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# 创建数组的时候指定数据类型
arr_2 = np.array([(1,2),(3.0,4),(5,6)],dtype = int)
arr_2

array([[1, 2],
       [3, 4],
       [5, 6]])

# 创建特殊数组

创建全零数组，np.zeros(shape, dtype = None)
shape:表示是数据的形状，如果说需要创建是一维数组，那么直接写长度就好了，如果是多维数组，那么就需要将参数用括号括起来，表示这几个参数一起是zeros中的第一个参数  
dtype:数据类型

In [35]:
# 创建一个形状为5的一维全零数组
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [36]:
# 创建一个形状为3行3列的2维全零数组
zero2 = np.zeros((3,3))
zero2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
zero3 = np.zeros((3,3))
zero3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

使用np.ones()创建一个全一数组，参数与全零数组参数一致

In [39]:
one = np.ones(3)
one

array([1., 1., 1.])

使用np.empty()创建随机空数组，参数和上面的ones一致  
作用是生产随机数组，里面的数据是随机的，且数据类型默认为float

In [40]:
em = np.empty((4,4))
em

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78019082e-306],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

为什么在py文件中再次运行数据会变？  
py文件在再次运行代码的时候内存中的数据  
但是在jpyter文件中不会

In [50]:
num = 10

In [49]:
num

10

### 数组属性查看

In [54]:
ar = np.array([1,2,3,4,5])
print('查看数组的维度:',ar.ndim)
print('查看数组的形状：',ar.shape)
print('查看数组的大小：',ar.size)
print('查看数组元素类型：',ar.dtype)
print('元素字节大小：',ar.itemsize)
print('查看数组缓存区位置：',ar.data)

查看数组的维度: 1
查看数组的形状： (5,)
查看数组的大小： 5
查看数组元素类型： int32
元素字节大小： 4
查看数组缓存区位置： <memory at 0x0000025560FA8AC8>


In [56]:
# reshape()
ar = np.arange(20).reshape(4,5)
print('查看数组的维度:',ar.ndim)
print('查看数组的形状：',ar.shape)# 前面2个用得最多
print('查看数组的大小：',ar.size)
print('查看数组元素类型：',ar.dtype)
print('元素字节大小：',ar.itemsize) # 后面2个几乎用不到
print('查看数组缓存区位置：',ar.data)
ar

查看数组的维度: 2
查看数组的形状： (4, 5)
查看数组的大小： 20
查看数组元素类型： int32
元素字节大小： 4
查看数组缓存区位置： <memory at 0x0000025560F26F28>


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 数组的运算

In [58]:
num = np.arange(6).reshape(2,3)
num2 = np.arange(1,7).reshape(2,3)
print(num)
num

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
num+num2

array([[ 1,  3,  5],
       [ 7,  9, 11]])

### 矢量化运算：numpy数组在进行计算的时候会对每一个元素进行计算

In [60]:
n = np.arange(6).reshape(3,2)
n2 = np.arange(1,7).reshape(2,3)
print(n)
n2

[[0 1]
 [2 3]
 [4 5]]


array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
n+n2

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

广播机制：
    数组在进行时，要求两个数组的形状相同，如果说2个数组的形状不同，那么可能会出现广播机制，该机制会对数组进行扩展，使原本形状不同的2个数组广播成形状相同。广播机制会扩展维度较小的数组，使其与维度最大的数组shape相同，以便使用元素级运算。

要求：
1.2个数组的某一维度等长。
2.某一个数组的维度为1.
当参与计算的2个数组满足上面任意一个要求时2个数组就会触发广播机制

In [65]:
num3 = np.array([[1],[2]])
num4 = np.array([[4,5,6],[7,8,9]])
print(num3)
num4

[[1]
 [2]]


array([[4, 5, 6],
       [7, 8, 9]])

In [66]:
num3 + num4

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [68]:
# 创建三维数组
arr_3 = np.arange(16).reshape(2,2,4)
print(arr_3)
arr_3.ndim

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


3

# 索引和切片

In [70]:
# 一维数组切片
arr_1 = np.array([1,2,3,4,5])
arr_1[3]
arr_1[2:4] #前闭后开
arr_1[2:4:2] #[起始值：结束值：步长]

array([3])

In [71]:
# 2维切片
arr_2 = np.arange(20).reshape(4,5)
print(arr_2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [72]:
arr_2[3][1]

16

In [78]:
arr_2[:][1]

array([5, 6, 7, 8, 9])

In [74]:
arr_2[1:4][1:3]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
arr_2[1]

array([5, 6, 7, 8, 9])

In [77]:
arr_2[1][:]

array([5, 6, 7, 8, 9])

In [79]:
#布尔索引
name = np.array(['python','java','c','html','JavaScript'])
name

array(['python', 'java', 'c', 'html', 'JavaScript'], dtype='<U10')

In [82]:
# 生产满足标准正态分布的数据
data = np.random.randn(5,4)
data

array([[ 0.91515973,  1.15287166, -0.66134831,  2.39974086],
       [-0.6230071 ,  0.02992082, -0.03740499, -0.23912719],
       [-0.55209168, -0.03031065,  0.73389531, -0.33650689],
       [ 0.93895781,  1.15215146, -0.46334994, -0.91033153],
       [ 1.56377868,  1.13271583,  0.98652829, -0.63529452]])

In [83]:
name == 'python'

array([ True, False, False, False, False])

In [85]:
data[name == 'python']

array([[ 0.91515973,  1.15287166, -0.66134831,  2.39974086]])

In [87]:
data[[ False, False, True, False, False]]

array([[-0.55209168, -0.03031065,  0.73389531, -0.33650689]])